schema:
    - lib/apollo/schema/*.graphqls
schemaEntrypoint: lib/apollo/schema/index.graphqls
documents: "**/*.graphql"
config:
    scalars:
        Date: 'Date'
        DateTime: 'Date'
        ID: 'number'
        Slug: 'string'
    mappers:
        Appeal: 'lib/db/entities#Appeal'
        Call: 'lib/db/entities#Call'
        Claim: 'lib/db/entities#Claim'
        File: 'lib/db/entities#File'
        Note: 'lib/db/entities#Note'
        Provider: 'lib/db/entities#Provider'
    useTypeImports: true
plugins:
    - typescript
    - typescript-operations
    - typescript-react-apollo
    - typescript-resolvers
cacheDir: .graphql
