name: Automated Tests and Linting
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
      name: Install dependencies
    - run: yarn test:ci
      name: Run unit tests
      continue-on-error: true
    - name: Linting
      run: yarn lint
      continue-on-error: true

  coverage:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    if: github.base_ref
    steps:
    - uses: actions/checkout@v1
    - uses: artiomtr/jest-coverage-report-action@v1.1
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #   threshold: 80 # optional parameter
